### ISSUE TITLE
Where is DTCWTForward? 

### ISSUE THREAD

**Issue by smejjout** [lostanlen/lostanlen2023waspaa#1]
It is used here and imported from "murenn" but I can't find it anywhere in this repository. 
https://github.com/lostanlen/lostanlen2023waspaa/blob/main/student.py#L159

**Comment by lostanlen** [comment]
hello @smejjout , it's here! https://github.com/kymatio/murenn

**Comment by lostanlen** [comment]
You can now install murenn with `pip install murenn`
https://pypi.org/project/murenn/
